<?php
echo "<!DOCTYPE HTML>\n"; 
echo "<HTML>\n"; 
echo "	<HEAD>\n"; 
echo "		<TITLE>Remmly App</TITLE>\n"; 
echo "		<meta charset=\"utf-8\">\n"; 
echo "		<meta name=\"description\" content=\"Best in browser notepad, iOS and Android App coming soon!\">\n"; 
echo "		<meta name=\"Keywords\" content=\"Remmly, cloud, notes, storage, free, \">\n"; 
echo "		<link rel=\"shortcut icon\" href=\"#\">\n"; 
echo "		<link rel=\"shortcut icon\" href=\"../img/favicon.ico\">\n"; 
echo "		<link rel=\"Stylesheet\" href=\"css/app.css\">\n"; 
echo "		<script src=\"retina.js\"></script>\n"; 
echo "<script>\n"; 
echo "  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"; 
echo "  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"; 
echo "  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"; 
echo "  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n"; 
echo "\n"; 
echo "  ga('create', 'UA-45486043-1', 'remmly.com');\n"; 
echo "  ga('send', 'pageview');\n"; 
echo "\n"; 
echo "</script>\n"; 
echo "	</HEAD>\n"; 
echo "	<HEADER>\n"; 
echo "		<div id=\"navbar\">\n"; 
echo "		<nav class=\"clearfix\">\n"; 
echo "		<ul>\n"; 
echo "				<li> <a href=\"/App\">Get the App!</a>\n"; 
echo "					<li> <a href=\"#\">About Us</a>\n"; 
echo "						<li> <a href=\"#\">News</a>\n"; 
echo "						<li> <a href=\"#\">API</a>\n"; 
echo "						<li> <a href=\"http://www.remmly.com/\">Beta </a>\n"; 
echo "						<li> <a href=\"#\">Support</a>\n"; 
echo "							\n"; 
echo "								\n"; 
echo "			</ul>\n"; 
echo "		</nav>\n"; 
echo "	</div>\n"; 
echo "	</HEADER>\n"; 
echo "		\n"; 
echo "	<section id=\"logo\">\n"; 
echo "	<h1><img src=\"img/logo.png\" alt=\"logo.png\"></H1>\n"; 
echo "		<h2> A Simple </h2>\n"; 
echo "		<h2>way to keep notes</h2>\n"; 
echo "		<h2> to yourself </h2>\n"; 
echo "	</section>\n"; 
echo "				\n"; 
echo "	<div id=\"content\">\n"; 
echo "		<iframe width=\"560\" height=\"315\" src=\"//www.youtube.com/embed/3A2lD3itViE\" frameborder=\"0\" allowfullscreen></iframe>\n"; 
echo "\n"; 
echo "	</div>\n"; 
echo "\n"; 
echo "<div id=\"Images\">\n"; 
echo "</div>\n"; 
echo "		\n"; 
echo "			<div id=\"footer\">\n"; 
echo "				<p>&copy; Bugger iOS APP</p> <h4>TTreads Designs 2013</h4>\n"; 
echo "			</div>\n"; 
echo "</HTML>\n";
?>
