<?php
echo "<!DOCTYPE html>\n"; 
echo "<html lang=\"en\">\n"; 
echo "	<head>\n"; 
echo "	<meta charset=\"utf-8\">\n"; 
echo "	<title>Remmly</title>\n";  
echo "	<meta name=\"description\" content=\"Best in browser notepad, iOS and Android App coming soon!\">\n"; 
echo "	<meta name=\"Keywords\" content=\"Remmly, cloud, notes, storage, free, \">\n"; 
echo "	<meta name=\"author\" content=\"TTreads Designs\">\n"; 
echo "	<link rel=\"shortcut icon\" href=\"img/favicon.ico\">\n"; 
echo "	<script src=\"retina.js\"></script>\n"; 
echo "	<script>\n"; 
echo "  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){\n"; 
echo "  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),\n"; 
echo "  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)\n"; 
echo "  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');\n";
echo "  ga('create', 'UA-45486043-1', 'remmly.com');\n"; 
echo "  ga('send', 'pageview');\n";
echo "</script>\n"; 
echo "	<!-- Le styles -->\n"; 
echo "	<link href=\"css/Remmly.css\" rel=\"stylesheet\">\n"; 
echo "	<style>\n"; 
echo "		body {\n"; 
echo "		padding-top: 60px; /* 60px to make the container go all the way to the bottom of the topbar */\n"; 
echo "		}\n";
echo "		.red{\n";
echo "		background-color : #FA5757;\n"; 
echo "		}\n";
echo "		.blue {\n";
echo "		border:1px solid white;\n"; 
echo "		}\n";
echo "		.green {\n";
echo "		background-color : #B5F2BB;\n"; 
echo "		}\n";
echo "		.yellow {\n";
echo "		background-color : #EDF2B5;\n"; 
echo "		}\n";
echo "		.orange {\n";
echo "		background-color : #F2D3B5;\n";
echo "	</style>\n";
echo "	<link href=\"css/bootstrap-responsive.css\" rel=\"stylesheet\">\n";
echo "	<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->\n"; 
echo "	<!--[if lt IE 9]>\n"; 
echo "		<script src=\"http://html5shim.googlecode.com/svn/trunk/html5.js\"></script>\n"; 
echo "	<![endif]-->\n";
echo "	<!-- Le fav and touch icons -->\n"; 
echo "	<script type=\"text/javascript\">\n";
echo "	  var _gaq = _gaq || [];\n"; 
echo "	  _gaq.push(['_setAccount', 'UA-22484023-1']);\n"; 
echo "	  _gaq.push(['_trackPageview']);\n";
echo "	  (function() {\n"; 
echo "	    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;\n"; 
echo "	    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';\n"; 
echo "	    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);\n"; 
echo "	  })();\n";
echo "	</script>	\n";
echo "	</head>\n"; 
echo "<header>\n"; 
echo "		<div id=\"navbar\">\n"; 
echo "		<nav class=\"clearfix\">\n"; 
echo "		<ul>\n"; 
echo "				<li> <a href=\"/App\">Get the App!</a>\n"; 
echo "					</li><li> <a href=\"#\">About Us</a>\n"; 
echo "						</li><li> <a href=\"#\">News</a>\n"; 
echo "						</li><li> <a href=\"#\">API</a>\n"; 
echo "						</li><li> <a href=\"http://www.remmly.com/\">Beta </a>\n"; 
echo "						</li><li> <a href=\"#\">Support</a>\n";
echo "			</li></ul>\n"; 
echo "		</nav>\n"; 
echo "	</div>\n"; 
echo "	</header>\n";
echo "	<body>\n";
echo "	<div class=\"container\">\n"; 
echo "		<div class='hero-unit'>\n"; 
echo "			<h1><a href=\"http://www.remmly.com/\"><img src=\"img/logo.png\" alt=\"logo.png\"></a></h1>\n"; 
echo "			<p></p>\n"; 
echo "		</div>\n";
echo "		<form onsubmit=\"return addTask()\">\n"; 
echo "				<input type=\"text\" name=\"title\" id=\"title\" placeholder=\"\" style=\"width: 980px; height: 40px;font-size: 40px; color: white; border:2px solid white; border-radius:10px\">\n"; 
echo "				<br />\n"; 
echo "				<textarea style=\"width : 0px;\" height=\"0px\" color: white; rows=\"4\" cols=\"200\" name=\"content\" id=\"content\" placeholder=\"\" ></textarea>    <input type=\"number\" id=\"hour\" name=\"hour\" min=\"0\" max=\"23\" style=\"width : 0px; margin-left:-9000px;\" placeholder=\"\" /> <input type=\"number\" name=\"minuts\" id=\"minuts\" min=\"0\" max=\"59\" style=\"width : 0px; margin-left:-9000px;\" placeholder=\"00\"/> \n"; 
echo "				<br />\n"; 
echo "			 	<button type=\"submit\" class=\"btn btn-primary\"> Rem it</button></form><button class=\"btn btn-danger\" onclick=\"cleanTasks()\">Clear all</button>\n";
echo "		</div>\n"; 
echo "		<br />\n";
echo "		<div class=\"span8 well\" id=\"contain\">\n"; 
echo "		 <h1></h1>\n"; 
echo "		 <div class=\"row\" id=\"redContainer\">\n";
echo "		</div>\n"; 
echo "		 <div class=\"row\" id=\"orangeContainer\">\n";
echo "		</div>\n"; 
echo "		 <div class=\"row\" id=\"yellowContainer\">\n";
echo "		</div>\n"; 
echo "		 <div class=\"row\" id=\"greenContainer\">\n";
echo "		</div>\n"; 
echo "		 <div class=\"row\" id=\"blueContainer\">\n";
echo "		</div>\n"; 
echo "		</div>\n"; 
echo "<!-- Timer -->\n";
echo "	<script>\n";
echo "calculateTimer = function(time){\n"; 
echo "		var str = \"\";\n"; 
echo "		var cents = time / 10 | 0;\n"; 
echo "		var seconds = time / 1000 | 0;\n"; 
echo "		var minuts = seconds / 60 | 0;\n"; 
echo "		var hours = minuts / 60 | 0;\n"; 
echo "		cents %= 100;\n"; 
echo "		seconds %= 60;\n"; 
echo "		minuts %= 60;\n"; 
echo "		hours %= 60;\n"; 
echo "		if (hours != 0)\n"; 
echo "			str += hours + \"h \" \n"; 
echo "		str += minuts + \"m \" + seconds + 's ';\n";
echo "		//console.log(timeToCents(minuts, seconds, cents));\n"; 
echo "		return str;\n"; 
echo "	}  \n";
echo "getCurrentHour = function(){\n"; 
echo "	var hours = new Date().toString().substring(16, 18);\n"; 
echo "	var minuts = new Date().toString().substring(19, 21);\n"; 
echo "	var seconds = new Date().toString().substring(22, 24);\n";
echo "	return convertHour(hours, minuts, seconds);\n"; 
echo "}  \n";
echo "convertHour = function(hours, minuts, seconds){\n"; 
echo "	if (hours >= 24)\n"; 
echo "		hours = 23;\n";
echo "	if (hours <0)\n"; 
echo "		hours = 0;\n";
echo "	if (minuts >= 60)\n"; 
echo "		minuts = 59;\n"; 
echo "	if (minuts < 0)\n"; 
echo "		minuts = 0;\n";
echo "	if (seconds >= 60)\n"; 
echo "		seconds = 59;\n"; 
echo "	if (seconds < 0)\n"; 
echo "		seconds = 0;\n";
echo "	return seconds * 1000 + minuts * 60000 + hours * 3600000;\n"; 
echo "}\n"; 
echo "	var containers = {\n";
echo "		\"red\" : document.getElementById('redContainer'),\n"; 
echo "		\"orange\" : document.getElementById('orangeContainer'),\n"; 
echo "		\"yellow\" : document.getElementById('yellowContainer'),\n"; 
echo "		\"green\" : document.getElementById('greenContainer'),\n"; 
echo "		\"blue\" : document.getElementById('blueContainer'),\n"; 
echo "	};\n";
echo "	var tasks = [];\n"; 
echo "	var CURRDATE = getCurrentHour();\n";
echo "	var stepClasses = [\n";
echo "		\"green\",\n"; 
echo "		\"yellow\",\n"; 
echo "		\"orange\",\n"; 
echo "		\"red\",\n"; 
echo "		\"blue\"\n"; 
echo "		];\n";
echo "	function cleanTasks(){\n"; 
echo "		for (var i in tasks){\n"; 
echo "			var p = tasks[i];\n"; 
echo "			if (p.finished){\n"; 
echo "				deleteTask(i);\n"; 
echo "				localStorage.clear();\n"; 
echo "			}\n"; 
echo "		}\n";
echo "		saveTasks();\n"; 
echo "	}\n"; 
echo "	function updateTask(p){\n";
echo "		var d = p.d;\n"; 
echo "		var s = p.s;\n"; 
echo "		var e = p.e;\n"; 
echo "		var h2 = p.h2;\n";
echo "		var step1 = Math.floor(s + ((e - s) * 0.25)); // Yellow\n"; 
echo "		var step2 = Math.floor(s + ((e - s) * 0.50)); // Orange\n"; 
echo "		var step3 = Math.floor(s + ((e - s) * 0.75)); // Red\n"; 
echo "		var step4 = e;\n";
echo "		if (CURRDATE > step4)\n"; 
echo "		p.step = stepClasses[4];\n"; 
echo "		if (CURRDATE <= step4)\n"; 
echo "		p.step = stepClasses[3];\n"; 
echo "		if (CURRDATE <= step3)\n"; 
echo "		p.step = stepClasses[2];\n"; 
echo "		if (CURRDATE <= step2)\n"; 
echo "		p.step = stepClasses[1];\n"; 
echo "		if (CURRDATE <= step1)\n"; 
echo "		p.step = stepClasses[0];\n";
echo "		h2.innerHTML = \"Temps restant : \" + calculateTimer(e - CURRDATE) + \"| Deadline : \" + calculateTimer(e);\n"; 
echo "		if (p.step == \"blue\"){\n"; 
echo "			h2.innerHTML = \"\";\n"; 
echo "			p.finished = true;\n"; 
echo "		}\n"; 
echo "		d.className = \"span6 well \" + p.step; \n";
echo "		if (p.step != p.lastStep){\n";
echo "			containers[p.lastStep].removeChild(d);\n"; 
echo "			containers[p.step].appendChild(d);\n"; 
echo "			p.lastStep = p.step;\n"; 
echo "		}\n";
echo "	}\n";
echo "	function addTask(){\n"; 
echo "		setTimeout(addT, 33);\n"; 
echo "		return false;\n";
echo "	}\n";
echo "	function addT(){\n";
echo "		var title = document.getElementById('title').value;\n"; 
echo "		var content = document.getElementById('content').value;\n"; 
echo "		var hour = document.getElementById('hour').value;\n"; 
echo "		var minuts = document.getElementById('minuts').value;\n";
echo "		console.log (title + \" - \" + content + \" - \" + hour + \"h \" + minuts);\n"; 
echo "		var seconds = 0;\n"; 
echo "		createTaskDisplay(title, CURRDATE, convertHour(hour, minuts, seconds), content);\n";
echo "		saveTasks();\n"; 
echo "		//console.log(\"allo\");\n"; 
echo "		return false;		\n"; 
echo "	}\n";
echo "	function saveTasks(){\n";
echo "		var t = [];\n"; 
echo "		if (localStorage && tasks[0] != undefined){\n"; 
echo "			t = [];\n"; 
echo "			for (var i in tasks){\n"; 
echo "				var p = tasks[i];\n"; 
echo "				t.push({\n"; 
echo "					t : p.t,\n"; 
echo "					s : p.s,\n"; 
echo "					e : p.e,\n"; 
echo "					c : p.c\n"; 
echo "				});\n";
echo "			}\n"; 
echo "			console.log(t);\n"; 
echo "			localStorage[\"tasks\"] = JSON.stringify(t);\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	function loadTasks(){\n";
echo "		if (localStorage){\n";
echo "			if (localStorage[\"tasks\"] != undefined){\n";
echo "				var t = JSON.parse(localStorage[\"tasks\"]);\n"; 
echo "				for (var i in t){\n"; 
echo "					var p = t[i];\n";
echo "					createTaskDisplay(p.t, p.s, p.e, p.c);\n"; 
echo "				}\n"; 
echo "			}\n"; 
echo "		}\n"; 
echo "	}\n";
echo "	function deleteTask(id){\n"; 
echo "		console.log(id);\n"; 
echo "		containers[tasks[id].step].removeChild(tasks[id].d);\n"; 
echo "		tasks[id] = tasks[tasks.length - 1];\n"; 
echo "		tasks.pop();\n";
echo "		for (var i in tasks){\n"; 
echo "			tasks[i].id = i;\n"; 
echo "			tasks[i].a.id = i;\n"; 
echo "		}\n"; 
echo "		saveTasks();\n"; 
echo "	}\n";
echo "	function createTaskDisplay(title, start, end, content){\n";
echo "		var d = document.createElement('div');\n"; 
echo "		d.id = \"task-\" + tasks.length;  \n"; 
echo "		var id = tasks.length;\n"; 
echo "		 \n"; 
echo "		tasks.push( {\n"; 
echo "		d : d,\n"; 
echo "		s : start,\n"; 
echo "		e : end,\n"; 
echo "		c : content,\n"; 
echo "		t : title,\n"; 
echo "		id : id,\n"; 
echo "		finished : false\n"; 
echo "		});\n"; 
echo "		var p = tasks[tasks.length - 1];\n"; 
echo "		// Green\n"; 
echo "		var step1 = Math.floor(start + ((end - start) * 0.25)); // Yellow\n"; 
echo "		var step2 = Math.floor(start + ((end - start) * 0.50)); // Orange\n"; 
echo "		var step3 = Math.floor(start + ((end - start) * 0.75)); // Red\n"; 
echo "		var step4 = end;\n";
echo "		if (CURRDATE > step4)\n"; 
echo "		p.step = stepClasses[4];\n"; 
echo "		if (CURRDATE <= step4)\n"; 
echo "		p.step = stepClasses[3];\n"; 
echo "		if (CURRDATE <= step3)\n"; 
echo "		p.step = stepClasses[2];\n"; 
echo "		if (CURRDATE <= step2)\n"; 
echo "		p.step = stepClasses[1];\n"; 
echo "		if (CURRDATE <= step1)\n"; 
echo "		p.step = stepClasses[0];\n";
echo "		p.lastStep = p.step;\n";
echo "		d.className = \"span6 well \" + p.step; \n";
echo "		var a = document.createElement('a');\n"; 
echo "		a.style.float = \"right\";\n";
echo "		a.id = id;\n"; 
echo "		a.onclick = function(){\n";
echo "			deleteTask(this.id)\n"; 
echo "		}\n"; 
echo "		//a.onClick = \"deleteTask(\" + p.id + \")\";\n";
echo "		var i = document.createElement('img');\n"; 
echo "		i.src = \"img/cross.png\";\n";
echo "		a.appendChild(i);\n"; 
echo "		d.appendChild(a);\n"; 
echo "		p.a = a;\n";
echo "		var h = document.createElement('h2');\n"; 
echo "		h.innerHTML = title;\n"; 
echo "		d.appendChild(h);\n"; 
echo "		p.h = h;\n";
echo "		var cont = document.createElement('p');\n"; 
echo "		cont.innerHTML = content;\n"; 
echo "		d.appendChild(cont);\n"; 
echo "		p.cont = cont;\n";
echo "		var h2 = document.createElement('h3');\n"; 
echo "		h2.innerHTML = \"Temps restant : \" + calculateTimer(end - CURRDATE) + \"| Deadline : \" + calculateTimer(end);\n"; 
echo "		d.appendChild(h2);\n"; 
echo "		p.h2 = h2;\n";
echo "		containers[p.step].appendChild(d);\n"; 
echo "	}\n";
echo "	function run(){\n";
echo "		CURRDATE = getCurrentHour();\n";
echo "		update();\n";
echo "		setTimeout(run, 33);\n"; 
echo "	}\n";
echo "	function update(){\n";
echo "		for (var i in tasks){\n"; 
echo "		updateTask(tasks[i]);\n"; 
echo "		}\n"; 
echo "	}\n"; 
echo "	loadTasks();\n"; 
echo "	run();\n";
echo "	</script>\n"; 
echo "	</body>\n"; 
echo "</html>\n";
?>
